export const REQUEST_RECEIVE_STUDENTS = 'REQUEST_RECEIVE_STUDENTS';
export const SUCCESS_RECEIVE_STUDENTS = 'SUCCESS_RECEIVE_STUDENTS';
export const ERROR_RECEIVE_STUDENTS = 'ERROR_RECEIVE_STUDENTS';

export const REQUEST_DELETE_STUDENT = 'REQUEST_DELETE_STUDENT';
export const SUCCESS_DELETE_STUDENT = 'SUCCESS_DELETE_STUDENT';
export const ERROR_DELETE_STUDENT = 'ERROR_DELETE_STUDENT';