export const REQUEST_RECEIVE_STUDENT = 'REQUEST_RECEIVE_STUDENT';
export const SUCCESS_RECEIVE_STUDENT = 'SUCCESS_RECEIVE_STUDENT';
export const ERROR_RECEIVE_STUDENT = 'ERROR_RECEIVE_STUDENT';

export const REQUEST_UPDATE_STUDENT = 'REQUEST_UPDATE_STUDENT';
export const SUCCESS_UPDATE_STUDENT = 'SUCCESS_UPDATE_STUDENT';
export const ERROR_UPDATE_STUDENT = 'ERROR_UPDATE_STUDENT';

export const REQUEST_CREATE_STUDENT = 'REQUEST_CREATE_STUDENT';
export const SUCCESS_CREATE_STUDENT = 'SUCCESS_CREATE_STUDENT';
export const ERROR_CREATE_STUDENT = 'ERROR_CREATE_STUDENT';

export const RESET_STUDENT_DATA = 'RESET_STUDENT_DATA'